[package]
name = "stellar-xdr"
description = "Stellar XDR types, encoding, and decoding."
homepage = "https://github.com/stellar/rs-stellar-xdr"
repository = "https://github.com/stellar/rs-stellar-xdr"
authors = ["Stellar Development Foundation <info@stellar.org>"]
license = "Apache-2.0"
version = "0.0.7"
edition = "2021"
rust-version = "1.65"

[[bin]]
name = "stellar-xdr"
path = "src/bin/main.rs"
required-features = ["cli"]

[build_dependencies]
crate-git-revision = "0.0.2"

[dependencies]
const_format = "0.2.30"
base64 = { version = "0.13.0", optional = true }
serde = { version = "1.0.139", features = ["derive"], optional = true }
serde_with = { version = "2.0.1", optional = true }
hex = { version = "0.4.3", optional = true }
num-bigint = { version = "0.4.3", optional = true }
arbitrary = {version = "1.1.3", features = ["derive"], optional = true}

clap = { version = "4.0.26", features = ["derive", "env"], optional = true }
serde_json = { version = "1.0.87", optional = true }

[dev_dependencies]
serde_json = "1.0.87"

[features]
default = ["std"]
std = ["alloc"]
alloc = ["dep:hex"]
next = []

# Features dependent on optional dependencies.
base64 = ["std", "dep:base64"]
serde = ["alloc", "dep:serde", "dep:serde_with", "hex/serde"]
num-bigint = ["alloc", "dep:num-bigint"]
arbitrary = ["std", "dep:arbitrary"]
hex = []

# Features enabled for the cli only.
cli = ["dep:clap", "dep:serde_json", "std", "base64", "serde"]

[package.metadata.docs.rs]
all-features = true
